<template>
  <div class="page resource-detail" :class="{ 'simple-detail': ['markets', 'products'].includes(resource) }" v-loading="loading">
    <div class="workspace-head">
      <div><span class="eyebrow">{{ label.toUpperCase() }} DETAIL</span><h1>{{ title || '详情' }}</h1></div>
      <div class="workspace-actions"><el-button @click="router.back()">返回</el-button><el-button type="primary" @click="openEdit">编辑</el-button></div>
    </div>
    <div v-if="item" class="detail-layout">
      <section class="workspace-panel detail-card"><h3>基本信息</h3><div v-for="field in fields" :key="field.key" class="detail-row"><span>{{ field.label }}</span><strong>{{ formatField(field.key) }}</strong></div></section>
      <section v-if="resource === 'assets'" class="workspace-panel preview-card"><h3>媒体预览</h3><img v-if="isImage" :src="mediaUrl" alt="素材预览"/><video v-else-if="isVideo" :src="mediaUrl" controls/><el-empty v-else description="暂无可预览文件" :image-size="70"/><div v-if="assetFiles.length" class="file-info"><span>已保存文件：{{ assetFiles[0].file_path }}</span><span>大小：{{ formatSize(assetFiles[0].file_size) }}</span></div></section>
      <section v-if="resource === 'scripts'" class="workspace-panel script-audio-card"><div class="section-head"><div><h3>口播音频</h3><span class="muted">播放时会自动定位当前文案</span></div><span class="audio-time">{{ currentTime.toFixed(1) }}s / {{ item.duration || 0 }}s</span></div><audio v-if="audioUrl" ref="audioPlayer" :src="audioUrl" controls preload="metadata" @timeupdate="syncAudioTime"/><el-empty v-else description="尚未导入口播音频" :image-size="60"/><span v-if="item.audio_file_name" class="muted">{{ item.audio_file_name }}</span></section>
      <section v-if="resource === 'scripts'" class="workspace-panel script-timeline-card"><div class="section-head"><div><h3>分段口播时间轴</h3><span class="muted">点击分段可试听对应位置</span></div><strong>{{ scriptSegments.length }} 段 · {{ item.duration || 0 }} 秒</strong></div><div class="script-timeline-ruler"><i v-for="tick in timelineTicks" :key="tick" :style="{ left: `${tickPercent(tick)}%` }"><span>{{ tick }}s</span></i></div><div class="script-detail-segments"><article v-for="(segment,index) in scriptSegments" :key="segment.id" class="script-detail-segment" :class="[`role-${segment.role}`,{active:currentSegmentIndex===index}]" @click="seekToSegment(segment,index)"><div class="script-segment-time"><b>{{ roleLabel(segment.role) }}</b><span>{{ Number(segment.start_second).toFixed(1) }}–{{ Number(segment.end_second).toFixed(1) }} 秒</span><el-tag v-if="segment.is_key" size="small" type="danger" effect="plain">重点</el-tag></div><div class="script-segment-copy"><p>{{ segment.spoken_text }}</p><div v-if="segment.highlight_text" class="highlight-words">重点词：{{ segment.highlight_text }}</div><small>{{ segment.visual_direction || '未填写画面要求' }}</small></div><div class="script-segment-asset"><span>建议素材</span><strong>{{ assetTypeLabel(segment.recommended_asset_type) }}</strong></div></article><el-empty v-if="!scriptSegments.length" description="尚未设置分段文案" :image-size="60"/></div></section>
      <section v-if="resource === 'videos'" class="workspace-panel text-card"><h3>成片信息</h3><div class="detail-row"><span>视频标题</span><strong>{{ item.title || '暂无' }}</strong></div><div class="detail-row"><span>关联混剪方案</span><strong>{{ item.mix_project?.name || '未关联' }}</strong></div><div class="detail-row"><span>状态</span><strong>{{ item.status || 'draft' }}</strong></div><div class="detail-row"><span>发布状态</span><strong>{{ item.publish_status || 'unpublished' }}</strong></div><div class="detail-row"><span>版本信息</span><strong>V{{ item.version || 1 }}</strong></div></section>
      <section v-if="resource === 'videos'" class="workspace-panel preview-card"><div class="section-head"><h3>成片预览</h3><label class="file-button">上传或替换<input type="file" accept=".mp4,.mov,.webm" @change="uploadVideo"/></label></div><video v-if="isVideo" :src="mediaUrl" controls/><el-empty v-else description="尚未上传成片文件" :image-size="70"/></section>
      <section v-if="resource === 'videos'" class="workspace-panel text-card"><div class="section-head"><h3>版本记录</h3><el-button size="small" @click="createVersion">记录当前版本</el-button></div><el-table :data="versions" stripe empty-text="暂无版本记录"><el-table-column prop="version" label="版本" width="90"/><el-table-column prop="change_note" label="变更说明"/><el-table-column prop="created_at" label="创建时间"/></el-table></section>
      <section v-if="resource === 'assets'" class="workspace-panel text-card"><h3>资产血缘</h3><div v-for="project in lineage.mix_projects || []" :key="project.id" class="lineage-row"><strong>{{ project.name }}</strong><span>{{ project.videos?.map((video:any)=>video.title).join('、') || '尚未关联成片' }}</span></div><el-empty v-if="!lineage.mix_projects?.length" description="尚未被混剪方案使用" :image-size="60"/></section>
    </div>
    <el-dialog v-model="editing" :title="`编辑${label}信息`" :width="resource === 'scripts' ? '960px' : '680px'">
      <el-form :model="form" label-width="90px"><el-form-item :label="['scripts','videos'].includes(resource) ? '标题' : '名称'"><el-input v-model="form[titleKey]"/></el-form-item><div v-if="resource !== 'markets'" class="form-grid"><el-form-item label="市场"><el-select v-model="form.market_id" clearable filterable><el-option v-for="entry in markets" :key="entry.id" :label="entry.name" :value="entry.id"/></el-select></el-form-item><el-form-item v-if="resource !== 'products'" label="产品"><el-select v-model="form.product_id" clearable filterable><el-option v-for="entry in products" :key="entry.id" :label="entry.name" :value="entry.id"/></el-select></el-form-item></div>
        <template v-if="resource === 'markets'"><el-form-item label="语言"><el-input v-model="form.language"/></el-form-item><el-form-item label="国家代码"><el-input v-model="form.country_code"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
        <template v-if="resource === 'products'"><el-form-item label="分类"><el-input v-model="form.category"/></el-form-item><el-form-item label="卖点"><el-input v-model="form.selling_points" type="textarea"/></el-form-item><el-form-item label="目标市场"><el-input v-model="form.target_markets"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
        <template v-if="resource === 'assets'"><el-form-item label="类型"><el-input v-model="form.asset_type"/></el-form-item><el-form-item label="来源平台"><el-input v-model="form.source_platform"/></el-form-item><el-form-item label="来源链接"><el-input v-model="form.source_url"/></el-form-item><div class="form-grid"><el-form-item label="时长"><el-input-number v-model="form.duration" :min="0"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="active"/><el-option label="归档" value="archived"/></el-select></el-form-item></div><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
        <template v-if="resource === 'scripts'"><div class="form-grid"><el-form-item label="类型"><el-input v-model="form.script_type"/></el-form-item><el-form-item label="总时长"><el-input-number v-model="form.duration" :min="1"/></el-form-item></div><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="口播音频"><div class="audio-upload"><input type="file" accept=".mp3,.wav,.m4a,.aac,.ogg,.webm" @change="selectAudio"/><span class="muted">{{ selectedAudio?.name || form.audio_file_name || '支持 MP3、WAV、M4A、AAC、OGG' }}</span><audio v-if="audioPreviewUrl || audioUrl" :src="audioPreviewUrl || audioUrl" controls/></div></el-form-item><div class="segment-editor-head"><div><strong>分段口播脚本</strong><span class="muted">时间不能重叠，最后一段建议与总时长一致</span></div><el-button size="small" @click="addSegment">添加分段</el-button></div><div class="segment-editor"><article v-for="(segment,index) in editSegments" :key="index" class="segment-edit-row"><div class="segment-edit-meta"><el-select v-model="segment.role"><el-option v-for="role in scriptRoles" :key="role.value" :label="role.label" :value="role.value"/></el-select><el-input-number v-model="segment.start_second" :min="0" :precision="1"/><span>至</span><el-input-number v-model="segment.end_second" :min="0.1" :precision="1"/><el-switch v-model="segment.is_key" active-text="重点"/></div><el-input v-model="segment.spoken_text" type="textarea" :rows="2" placeholder="这一时间段的口播文案"/><div class="segment-edit-detail"><el-input v-model="segment.visual_direction" placeholder="画面要求"/><el-select v-model="segment.recommended_asset_type" clearable placeholder="素材类型"><el-option label="使用过程" value="usage"/><el-option label="完成效果" value="result"/><el-option label="引导下单" value="cta"/></el-select><el-input v-model="segment.highlight_text" placeholder="高亮词，用逗号分隔"/><el-button link type="danger" @click="editSegments.splice(index,1)">删除</el-button></div></article></div></template>
        <template v-if="resource === 'videos'"><el-form-item label="时长"><el-input-number v-model="form.duration" :min="0"/></el-form-item><el-form-item label="状态"><el-input v-model="form.status"/></el-form-item><el-form-item label="发布状态"><el-input v-model="form.publish_status"/></el-form-item><el-form-item label="备注"><el-input v-model="form.notes" type="textarea"/></el-form-item></template>
      </el-form><template #footer><el-button @click="editing=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import axios from 'axios'; import { ElMessage } from 'element-plus';
const route=useRoute(),router=useRouter();const resource=computed(()=>String(route.params.resource)),id=computed(()=>route.params.id);const names:Record<string,string>={markets:'市场',products:'产品',assets:'素材',scripts:'口播脚本',videos:'视频作品'};const label=computed(()=>names[resource.value]||resource.value);const titleKey=computed(()=>['scripts','videos'].includes(resource.value)?'title':'name');
const item=ref<any>(null),form=ref<any>({}),loading=ref(false),saving=ref(false),editing=ref(false),versions=ref<any[]>([]),lineage=ref<any>({}),assetFiles=ref<any[]>([]),markets=ref<any[]>([]),products=ref<any[]>([]),scriptSegments=ref<any[]>([]),editSegments=ref<any[]>([]),selectedAudio=ref<File|null>(null),audioPreviewUrl=ref(''),audioPlayer=ref<HTMLAudioElement|null>(null),currentTime=ref(0),currentSegmentIndex=ref(-1);const scriptRoles=[{value:'hook',label:'Hook'},{value:'body',label:'Body'},{value:'ending',label:'Ending'},{value:'cta',label:'CTA'}];
const configs:Record<string,any[]>={markets:[['language','语言'],['country_code','国家代码'],['description','描述']],products:[['market_id','所属市场'],['category','分类'],['selling_points','卖点'],['target_markets','目标市场'],['tags','标签'],['description','描述']],assets:[['asset_type','类型'],['source_platform','来源平台'],['status','状态'],['duration','时长'],['description','描述'],['tags_text','标签']],scripts:[['script_type','脚本类型'],['duration','总时长'],['market_id','市场'],['product_id','产品']],videos:[['version','版本'],['status','状态'],['publish_status','发布状态'],['duration','时长'],['notes','备注']]};const fields=computed(()=>(configs[resource.value]||[]).map(([key,label])=>({key,label})));const title=computed(()=>item.value?.[titleKey.value]);const mediaUrl=computed(()=>storageUrl(item.value?.file_path));const audioUrl=computed(()=>storageUrl(item.value?.audio_path));const isImage=computed(()=>/\.(jpg|jpeg|png|webp)$/i.test(mediaUrl.value));const isVideo=computed(()=>/\.(mp4|mov|webm)$/i.test(mediaUrl.value));const timelineTicks=computed(()=>{const duration=Number(item.value?.duration)||0,step=duration<=30?5:10,ticks=[];for(let value=0;value<=duration;value+=step)ticks.push(value);if(ticks.at(-1)!==duration)ticks.push(duration);return ticks;});
function storageUrl(path:string|undefined){return path?`/storage/${String(path).replaceAll('\\','/')}`:'';}function format(value:any){return value===null||value===undefined||value===''?'暂无':String(value);}function formatField(key:string){if(key==='market_id')return item.value?.market?.name||format(item.value?.market_id);if(key==='product_id')return item.value?.product?.name||format(item.value?.product_id);return format(item.value?.[key]);}function roleLabel(role:string){return scriptRoles.find(item=>item.value===role)?.label||role;}function assetTypeLabel(type:string){return({usage:'使用过程',result:'完成效果',cta:'引导下单'} as any)[type]||type||'未设置';}function tickPercent(tick:number){return Math.min(100,tick/Math.max(Number(item.value?.duration)||1,1)*100);}function formatSize(size:number){return!size?'未知':size>1048576?`${(size/1048576).toFixed(1)} MB`:`${Math.round(size/1024)} KB`;}
async function load(){loading.value=true;try{const [record,marketRows,productRows]=await Promise.all([axios.get(`/api/${resource.value}/${id.value}`),axios.get('/api/markets'),axios.get('/api/products')]);item.value=record.data;form.value={...item.value,tags:item.value.tags_text??item.value.tags};markets.value=marketRows.data;products.value=productRows.data;if(resource.value==='scripts')scriptSegments.value=(await axios.get(`/api/scripts/${id.value}/segments`)).data;if(resource.value==='assets'){lineage.value=(await axios.get(`/api/assets/${id.value}/lineage`)).data;assetFiles.value=(await axios.get('/api/asset-files',{params:{asset_id:id.value}})).data;}if(resource.value==='videos')versions.value=(await axios.get('/api/content-versions',{params:{video_work_id:id.value}})).data;}catch(error:any){ElMessage.error(error?.response?.data?.detail||'详情加载失败');}finally{loading.value=false;}}
function clearAudioPreview(){if(audioPreviewUrl.value)URL.revokeObjectURL(audioPreviewUrl.value);selectedAudio.value=null;audioPreviewUrl.value='';}function openEdit(){clearAudioPreview();form.value={...item.value,tags:item.value?.tags_text??item.value?.tags};editSegments.value=scriptSegments.value.map(segment=>({...segment}));editing.value=true;}function addSegment(){const start=editSegments.value.length?Number(editSegments.value[editSegments.value.length-1].end_second):0;editSegments.value.push({role:'body',start_second:start,end_second:start+3,spoken_text:'',visual_direction:'',recommended_asset_type:'usage',is_key:false,highlight_text:''});}function selectAudio(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;clearAudioPreview();selectedAudio.value=file;audioPreviewUrl.value=URL.createObjectURL(file);}function syncAudioTime(){currentTime.value=audioPlayer.value?.currentTime||0;currentSegmentIndex.value=scriptSegments.value.findIndex(segment=>currentTime.value>=segment.start_second&&currentTime.value<segment.end_second);}function seekToSegment(segment:any,index:number){currentSegmentIndex.value=index;if(audioPlayer.value){audioPlayer.value.currentTime=segment.start_second;audioPlayer.value.play();}}
function segmentPayload(segment:any,index:number){return{script_id:Number(id.value),order_index:index,role:segment.role,start_second:segment.start_second,end_second:segment.end_second,spoken_text:String(segment.spoken_text||'').trim(),visual_direction:segment.visual_direction||null,recommended_asset_type:segment.recommended_asset_type||null,is_key:Boolean(segment.is_key),highlight_text:segment.highlight_text||null,notes:segment.notes||null};}
async function save(){const payload:any={};payload[titleKey.value]=form.value[titleKey.value];const editable:Record<string,string[]>={markets:['language','country_code','description'],products:['market_id','category','selling_points','target_markets','tags','description'],assets:['asset_type','source_platform','source_url','market_id','product_id','duration','status','description','tags'],scripts:['market_id','product_id','script_type','duration','tags','notes'],videos:['market_id','product_id','duration','status','publish_status','notes']};(editable[resource.value]||[]).forEach(key=>{if(form.value[key]!==undefined)payload[key]=form.value[key];});saving.value=true;try{item.value=(await axios.put(`/api/${resource.value}/${id.value}`,payload)).data;if(resource.value==='scripts'){const entries=editSegments.value.filter(segment=>String(segment.spoken_text||'').trim()).map(segmentPayload);await axios.put(`/api/scripts/${id.value}/segments`,entries);if(selectedAudio.value){const data=new FormData();data.append('file',selectedAudio.value);await axios.post(`/api/scripts/${id.value}/audio`,data);}}editing.value=false;clearAudioPreview();ElMessage.success('保存成功');await load();}catch(error:any){ElMessage.error(error?.response?.data?.detail||'保存失败');}finally{saving.value=false;}}
async function uploadVideo(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const data=new FormData();data.append('file',file);try{item.value=(await axios.post(`/api/videos/${id.value}/file`,data)).data;ElMessage.success('成片已上传');}catch(error:any){ElMessage.error(error?.response?.data?.detail||'上传失败');}}async function createVersion(){try{await axios.post(`/api/videos/${id.value}/versions`,{change_note:'详情页手动记录',snapshot:item.value});versions.value=(await axios.get('/api/content-versions',{params:{video_work_id:id.value}})).data;ElMessage.success('版本已记录');}catch{ElMessage.error('版本记录失败');}}
onMounted(load);onUnmounted(clearAudioPreview);
</script>
