<template>
  <div class="page resource-detail" v-loading="loading">
    <div class="workspace-head"><div><span class="eyebrow">{{ label.toUpperCase() }} DETAIL</span><h1>{{ title || '详情' }}</h1></div><div class="workspace-actions"><el-button @click="router.back()">返回</el-button><el-button type="primary" @click="editing = true">编辑</el-button></div></div>
    <div v-if="item" class="detail-layout">
      <section class="workspace-panel detail-card"><h3>基本信息</h3><div v-for="field in fields" :key="field.key" class="detail-row"><span>{{ field.label }}</span><strong>{{ format(item[field.key]) }}</strong></div></section>
      <section v-if="resource === 'assets'" class="workspace-panel preview-card"><h3>媒体预览</h3><img v-if="isImage" :src="mediaUrl" alt="素材预览" @error="previewError = '图片无法加载，请检查文件格式'"/><video v-else-if="isVideo" :src="mediaUrl" controls @error="previewError = '浏览器无法解码该视频，文件已保存；建议使用 H.264 MP4 格式'"/><el-empty v-else description="暂无可预览文件" :image-size="70"/><p v-if="previewError" class="preview-error">{{ previewError }}</p><div v-if="assetFiles.length" class="file-info"><span>已保存文件：{{ assetFiles[0].file_path }}</span><span>大小：{{ formatSize(assetFiles[0].file_size) }}</span></div></section>
      <section v-if="resource === 'scripts'" class="workspace-panel text-card"><h3>口播内容</h3><div class="script-block"><b>Hook</b><p>{{ item.hook || '暂无' }}</p></div><div class="script-block"><b>Body</b><p>{{ item.body || '暂无' }}</p></div><div class="script-block"><b>Ending / CTA</b><p>{{ [item.ending, item.cta].filter(Boolean).join(' ') || '暂无' }}</p></div></section>
      <section v-if="resource === 'templates'" class="workspace-panel text-card"><h3>模板结构</h3><pre>{{ item.structure || '暂无结构说明' }}</pre></section>
      <section v-if="resource === 'videos'" class="workspace-panel text-card"><h3>成片信息</h3><div class="detail-row"><span>视频标题</span><strong>{{ item.title || '暂无' }}</strong></div><div class="detail-row"><span>关联混剪方案</span><strong>{{ item.mix_project?.name || '未关联' }}</strong></div><div class="detail-row"><span>状态</span><strong>{{ item.status || 'draft' }}</strong></div><div class="detail-row"><span>发布状态</span><strong>{{ item.publish_status || 'unpublished' }}</strong></div><div class="detail-row"><span>版本信息</span><strong>V{{ item.version || 1 }}</strong></div></section>
      <section v-if="resource === 'videos'" class="workspace-panel text-card"><div class="section-head"><h3>版本记录</h3><el-button size="small" @click="createVersion">记录当前版本</el-button></div><el-table :data="versions" stripe empty-text="暂无版本记录"><el-table-column prop="version" label="版本" width="90"/><el-table-column prop="change_note" label="变更说明"/><el-table-column prop="created_at" label="创建时间"/></el-table></section>
      <section v-if="resource === 'assets'" class="workspace-panel text-card"><h3>资产血缘</h3><div v-if="lineage.mix_projects?.length" v-for="project in lineage.mix_projects" :key="project.id" class="lineage-row"><strong>{{ project.name }}</strong><span>{{ project.videos?.map((video: any) => video.title).join('、') || '尚未关联成片' }}</span></div><el-empty v-else description="尚未被混剪方案使用" :image-size="60"/></section>
    </div>
    <el-dialog v-model="editing" :title="`编辑${label}信息`" width="640px"><el-form v-if="resource === 'assets'" :model="form" label-width="90px"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="类型"><el-input v-model="form.asset_type"/></el-form-item><el-form-item label="来源平台"><el-input v-model="form.source_platform" placeholder="TikTok / Douyin"/></el-form-item><el-form-item label="来源链接"><el-input v-model="form.source_url"/></el-form-item><el-form-item label="市场 ID"><el-input-number v-model="form.market_id" :min="1" :controls="false"/></el-form-item><el-form-item label="产品 ID"><el-input-number v-model="form.product_id" :min="1" :controls="false"/></el-form-item><div class="form-grid"><el-form-item label="时长（秒）"><el-input-number v-model="form.duration" :min="0" :precision="2"/></el-form-item><el-form-item label="宽度"><el-input-number v-model="form.width" :min="0"/></el-form-item><el-form-item label="高度"><el-input-number v-model="form.height" :min="0"/></el-form-item><el-form-item label="帧率"><el-input-number v-model="form.fps" :min="0" :precision="2"/></el-form-item></div><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="active"/><el-option label="归档" value="archived"/></el-select></el-form-item><el-form-item label="标签"><el-input v-model="form.tags" placeholder="demo, sunscreen"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item></el-form><el-form v-else :model="form" label-width="90px"><el-form-item :label="resource === 'scripts' || resource === 'videos' ? '标题' : '名称'"><el-input v-model="form[titleKey]"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="editing=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import axios from 'axios'; import { ElMessage } from 'element-plus';
const route = useRoute(); const router = useRouter(); const resource = computed(() => String(route.params.resource)); const id = computed(() => route.params.id); const names: Record<string,string> = { assets:'素材', scripts:'口播脚本', templates:'内容模板', videos:'视频作品' }; const label = computed(() => names[resource.value] || resource.value); const titleKey = computed(() => resource.value === 'scripts' || resource.value === 'videos' ? 'title' : 'name'); const item = ref<any>(null), form = ref<any>({}), loading = ref(false), editing = ref(false), versions = ref<any[]>([]), lineage = ref<any>({}), assetFiles = ref<any[]>([]), previewError = ref('');
const configs: Record<string, any[]> = { assets:[['asset_type','类型'],['source_platform','来源平台'],['source_url','来源链接'],['status','状态'],['duration','时长'],['description','描述'],['tags_text','标签']], scripts:[['script_type','脚本类型'],['source_platform','来源平台'],['duration','时长'],['full_text','完整文案'],['notes','备注']], templates:[['template_type','模板类型'],['recommended_duration','建议时长'],['description','描述'],['tags_text','标签']], videos:[['version','版本'],['status','状态'],['publish_status','发布状态'],['duration','时长'],['file_path','文件路径'],['notes','备注']]}; const fields = computed(() => (configs[resource.value] || []).map(([key,label]) => ({key,label})));
const title = computed(() => item.value?.[titleKey.value]); const mediaUrl = computed(() => item.value?.file_path ? `/storage/${String(item.value.file_path).replaceAll('\\','/')}` : ''); const isImage = computed(() => /\.(jpg|jpeg|png|webp)$/i.test(mediaUrl.value)); const isVideo = computed(() => /\.(mp4|mov|webm)$/i.test(mediaUrl.value));
function format(value: any) { return value === null || value === undefined || value === '' ? '暂无' : String(value); }
async function load() { loading.value = true; try { item.value = (await axios.get(`/api/${resource.value}/${id.value}`)).data; form.value = { ...item.value }; if (resource.value === 'assets') { lineage.value = (await axios.get(`/api/assets/${id.value}/lineage`)).data; assetFiles.value = (await axios.get('/api/asset-files', { params: { asset_id: id.value } })).data; } if (resource.value === 'videos') versions.value = (await axios.get('/api/content-versions', { params: { video_work_id: id.value } })).data; } catch { ElMessage.error('详情加载失败'); } finally { loading.value = false; } }
async function save() { const payload: any = {}; if (resource.value === 'assets') { ['name','asset_type','source_platform','source_url','market_id','product_id','duration','width','height','fps','status','description','tags'].forEach(key => { if (form.value[key] !== undefined) payload[key] = form.value[key]; }); } else { payload[titleKey.value] = form.value[titleKey.value]; if (resource.value === 'scripts') ['script_type','hook','body','ending','cta','duration','full_text','notes'].forEach(key => { if (form.value[key] !== undefined) payload[key] = form.value[key]; }); if (resource.value === 'templates') ['template_type','structure','recommended_duration','description'].forEach(key => { if (form.value[key] !== undefined) payload[key] = form.value[key]; }); if (resource.value === 'videos') ['duration','status','publish_status','notes'].forEach(key => { if (form.value[key] !== undefined) payload[key] = form.value[key]; }); } try { item.value = (await axios.put(`/api/${resource.value}/${id.value}`, payload)).data; editing.value = false; ElMessage.success('保存成功'); } catch (error: any) { ElMessage.error(error?.response?.data?.detail || '保存失败'); } }
async function createVersion() { try { await axios.post(`/api/videos/${id.value}/versions`, { change_note: '详情页手动记录', snapshot: item.value }); versions.value = (await axios.get('/api/content-versions', { params: { video_work_id: id.value } })).data; ElMessage.success('版本已记录'); } catch { ElMessage.error('版本记录失败'); } }
function formatSize(size: number) { if (!size) return '未知'; return size > 1024 * 1024 ? `${(size / 1024 / 1024).toFixed(1)} MB` : `${Math.round(size / 1024)} KB`; }
onMounted(load);
</script>
