<template>
  <div class="page">
    <div v-if="!isAssistant" class="toolbar"><el-input v-model="query" placeholder="搜索名称、描述或标签" clearable @keyup.enter="load"/><el-button type="primary" @click="openCreate">新增{{ label }}</el-button></div>
    <section v-if="isSearchable" class="filter-bar">
      <el-select v-model="filters.market_id" placeholder="全部市场" clearable filterable><el-option v-for="item in markets" :key="item.id" :label="item.name" :value="item.id"/></el-select>
      <el-select v-model="filters.product_id" placeholder="全部产品" clearable filterable><el-option v-for="item in products" :key="item.id" :label="item.name" :value="item.id"/></el-select>
      <el-input v-model="filters.type" placeholder="内容类型" clearable/><el-input v-if="resource !== 'templates'" v-model="filters.source_platform" placeholder="来源平台" clearable/>
      <el-select v-if="resource !== 'templates'" v-model="filters.tag_id" placeholder="全部标签" clearable filterable><el-option v-for="item in tags" :key="item.id" :label="item.name" :value="item.id"/></el-select>
      <el-input-number v-model="filters.duration_min" placeholder="最短秒数" :min="0" :controls="false"/><el-input-number v-model="filters.duration_max" placeholder="最长秒数" :min="0" :controls="false"/>
      <el-button @click="load">筛选</el-button><el-button text @click="resetFilters">重置</el-button>
    </section>
    <template v-if="isAssistant">
      <section class="assistant-panel"><div><span class="eyebrow">CONTENT CREATION ASSISTANT</span><h2>从需求到混剪方案</h2><p>选择市场、产品、内容类型和时长，系统根据规则匹配现有脚本、模板与素材。</p></div>
        <div class="assistant-form"><el-select v-model="criteria.market_id" placeholder="选择市场" clearable filterable><el-option v-for="item in markets" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="criteria.product_id" placeholder="选择产品" clearable filterable><el-option v-for="item in products" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-input v-model="criteria.content_type" placeholder="内容类型，如 pain_point"/><el-input-number v-model="criteria.duration" :min="1" :max="600"/><el-input v-model="criteria.keywords" placeholder="关键词，用逗号分隔"/><el-button type="primary" @click="load">获取推荐</el-button></div>
      </section>
      <div class="recommend-grid"><section v-for="section in recommendationSections" :key="section.key" class="recommend-section"><div class="section-head"><h3>{{ section.title }}</h3><span class="muted">Top {{ section.limit }}</span></div>
        <div v-if="(recommendations[section.key] || []).length" class="recommend-list"><div v-for="(item,itemIndex) in (recommendations[section.key] || []).slice(0,section.limit)" :key="item.id" class="recommend-item"><div class="recommend-main"><strong>{{ item.name || item.title || item.id }}</strong><span class="score">{{ percent(item.score) }}</span></div><small>{{ (item.reasons || []).join(' · ') || '基础匹配' }}</small><div v-if="item.score_breakdown" class="score-breakdown"><span v-for="(value,key) in item.score_breakdown" :key="key">{{ scoreLabels[String(key)] || key }} {{ percent(value) }}</span></div><div v-if="section.key === 'mix_plans'" class="plan-summary">{{ item.asset_ids?.length || 0 }} 个素材 · {{ item.timeline?.length || 0 }} 段时间轴 · {{ item.target_duration || 0 }} 秒</div><el-button v-if="section.key === 'mix_plans'" size="small" type="primary" plain :loading="adopting === itemIndex" @click="adoptPlan(itemIndex)">采用并创建方案</el-button></div></div><el-empty v-else description="暂无匹配结果" :image-size="60"/>
      </section></div>
    </template>
    <el-table v-else :data="rows" stripe v-loading="loading" empty-text="暂无数据">
      <el-table-column :label="['scripts','videos'].includes(resource) ? '标题' : '名称'" min-width="180"><template #default="scope">{{ scope.row.name || scope.row.title }}</template></el-table-column><el-table-column v-if="resource === 'assets'" prop="asset_type" label="类型"/><el-table-column v-if="resource === 'scripts'" prop="script_type" label="类型"/><el-table-column v-if="resource === 'templates'" prop="template_type" label="类型"/><el-table-column v-if="resource === 'markets'" prop="country_code" label="国家代码"/><el-table-column v-if="resource === 'products'" prop="category" label="分类"/><el-table-column v-if="['assets','scripts'].includes(resource)" prop="source_platform" label="来源"/><el-table-column v-if="['assets','videos','mix-projects'].includes(resource)" prop="status" label="状态"/><el-table-column label="操作" width="190" fixed="right"><template #default="scope"><el-button v-if="hasDetail" link type="primary" @click="showDetail(scope.row)">详情</el-button><el-button link @click="openEdit(scope.row)">编辑</el-button><el-button link type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column>
    </el-table>
    <el-dialog v-model="dialog" :title="`${editing ? '编辑' : '新增'}${label}`" width="680px"><el-form :model="form" label-width="100px"><el-form-item :label="['scripts','videos'].includes(resource) ? '标题' : '名称'"><el-input v-model="form[titleKey]"/></el-form-item>
      <template v-if="resource === 'markets'"><el-form-item label="语言"><el-input v-model="form.language"/></el-form-item><el-form-item label="国家代码"><el-input v-model="form.country_code"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
      <template v-if="resource === 'products'"><el-form-item label="所属市场"><el-select v-model="form.market_id" clearable filterable><el-option v-for="item in markets" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="分类"><el-input v-model="form.category"/></el-form-item><el-form-item label="卖点"><el-input v-model="form.selling_points" type="textarea"/></el-form-item><el-form-item label="目标市场"><el-input v-model="form.target_markets"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
      <template v-if="resource === 'assets'"><el-form-item label="类型"><el-input v-model="form.asset_type" placeholder="pain_point / product / demo"/></el-form-item><el-form-item label="来源平台"><el-input v-model="form.source_platform" placeholder="TikTok / Douyin"/></el-form-item><el-form-item label="来源链接"><el-input v-model="form.source_url"/></el-form-item><div class="form-grid"><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item><el-form-item label="时长（秒）"><el-input-number v-model="form.duration" :min="0" :precision="2"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="active"/><el-option label="归档" value="archived"/></el-select></el-form-item></div><el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="2"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags" placeholder="demo, sunscreen"/></el-form-item></template>
      <template v-if="resource === 'scripts'"><div class="form-grid"><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item></div><el-form-item label="类型"><el-input v-model="form.script_type"/></el-form-item><el-form-item label="Hook"><el-input v-model="form.hook" type="textarea"/></el-form-item><el-form-item label="Body"><el-input v-model="form.body" type="textarea"/></el-form-item><el-form-item label="Ending"><el-input v-model="form.ending" type="textarea"/></el-form-item><el-form-item label="CTA"><el-input v-model="form.cta"/></el-form-item><el-form-item label="时长"><el-input-number v-model="form.duration" :min="0"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item></template>
      <template v-if="resource === 'templates'"><div class="form-grid"><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item></div><el-form-item label="类型"><el-input v-model="form.template_type"/></el-form-item><el-form-item label="结构"><el-input v-model="form.structure" type="textarea" :rows="3"/></el-form-item><el-form-item label="建议时长"><el-input-number v-model="form.recommended_duration" :min="0"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
      <template v-if="resource === 'videos'"><div class="form-grid"><el-form-item label="混剪方案"><el-select v-model="form.mix_project_id" clearable filterable><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item><el-form-item label="时长"><el-input-number v-model="form.duration" :min="0"/></el-form-item></div><el-form-item label="状态"><el-input v-model="form.status"/></el-form-item><el-form-item label="发布状态"><el-input v-model="form.publish_status"/></el-form-item><el-form-item label="备注"><el-input v-model="form.notes" type="textarea"/></el-form-item></template>
      <el-form-item v-if="!editing && ['assets','videos'].includes(resource)" label="上传文件"><input type="file" :accept="resource === 'assets' ? '.jpg,.jpeg,.png,.webp,.mp4,.mov,.webm' : '.mp4,.mov,.webm'" @change="previewFile"/><div v-if="previewUrl" class="upload-preview"><img v-if="selectedFile?.type.startsWith('image/')" :src="previewUrl" alt="预览"/><video v-else :src="previewUrl" controls/></div></el-form-item>
    </el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, onMounted, ref, watch } from 'vue'; import { useRouter } from 'vue-router'; import axios from 'axios'; import { ElMessage, ElMessageBox, ElOption, ElSelect } from 'element-plus';
const props=defineProps<{resource:string}>(); const resource=computed(()=>props.resource); const router=useRouter(); const isAssistant=computed(()=>resource.value==='assistant');
const names:Record<string,string>={markets:'市场',products:'产品',assets:'素材',scripts:'口播脚本',templates:'内容模板','mix-projects':'混剪方案',videos:'视频作品',assistant:'创作助手'}; const label=computed(()=>names[resource.value]||resource.value); const titleKey=computed(()=>['scripts','videos'].includes(resource.value)?'title':'name'); const endpoint=computed(()=>`/api/${resource.value}`); const isSearchable=computed(()=>['assets','scripts','templates'].includes(resource.value)); const hasDetail=computed(()=>['assets','scripts','templates','videos','mix-projects'].includes(resource.value));
const rows=ref<any[]>([]),query=ref(''),loading=ref(false),saving=ref(false),dialog=ref(false),editing=ref(false),form=ref<any>({}); const markets=ref<any[]>([]),products=ref<any[]>([]),tags=ref<any[]>([]),projects=ref<any[]>([]); const filters=ref<any>({market_id:null,product_id:null,type:'',source_platform:'',tag_id:null,duration_min:null,duration_max:null}); const criteria=ref<any>({market_id:null,product_id:null,content_type:'',duration:20,keywords:'sunscreen'}),recommendations=ref<any>({}),adopting=ref<number|null>(null); const selectedFile=ref<File|null>(null),previewUrl=ref('');
const recommendationSections=[{key:'templates',title:'推荐模板',limit:3},{key:'scripts',title:'推荐脚本',limit:5},{key:'assets',title:'推荐素材',limit:10},{key:'mix_plans',title:'推荐混剪方案',limit:3}]; const scoreLabels:Record<string,string>={market:'市场',product:'产品',content_type:'类型',semantic:'语义',duration:'时长'};
const allowedFields:Record<string,string[]>={markets:['name','language','country_code','description'],products:['name','category','selling_points','target_markets','tags','description','market_id'],assets:['name','asset_type','source_platform','source_url','market_id','product_id','duration','status','description','tags'],scripts:['title','source_platform','source_url','market_id','product_id','script_type','hook','body','ending','cta','duration','full_text','tags','notes'],templates:['name','market_id','product_id','template_type','structure','recommended_duration','description','tags'],videos:['title','mix_project_id','market_id','product_id','duration','status','publish_status','notes'],'mix-projects':['name']};
const LookupSelect=defineComponent({props:{modelValue:{default:null},items:{type:Array,default:()=>[]}},emits:['update:modelValue'],setup(p,{emit}){return()=>h(ElSelect,{modelValue:p.modelValue,clearable:true,filterable:true,'onUpdate:modelValue':(v:any)=>emit('update:modelValue',v)},()=> (p.items as any[]).map(item=>h(ElOption,{key:item.id,label:item.name,value:item.id})));}});
async function loadLookups(){const [m,p,t,mp]=await Promise.all([axios.get('/api/markets'),axios.get('/api/products'),axios.get('/api/tags'),axios.get('/api/mix-projects')]);markets.value=m.data;products.value=p.data;tags.value=t.data;projects.value=mp.data;}
function requestParams(){const p:any={q:query.value||undefined,market_id:filters.value.market_id||undefined,product_id:filters.value.product_id||undefined,source_platform:filters.value.source_platform||undefined,tag_id:filters.value.tag_id||undefined,duration_min:filters.value.duration_min??undefined,duration_max:filters.value.duration_max??undefined};if(filters.value.type)p[resource.value==='assets'?'asset_type':resource.value==='scripts'?'script_type':'template_type']=filters.value.type;return p;}
async function load(){loading.value=true;try{if(isAssistant.value){const payload={market_id:criteria.value.market_id||null,product_id:criteria.value.product_id||null,content_type:criteria.value.content_type||null,duration:criteria.value.duration||null,keywords:String(criteria.value.keywords||'').split(',').map((w:string)=>w.trim()).filter(Boolean)};recommendations.value=(await axios.post('/api/assistant/recommend',payload)).data;}else rows.value=(await axios.get(endpoint.value,{params:requestParams()})).data;}catch(e:any){ElMessage.error(e?.response?.data?.detail||'加载失败');}finally{loading.value=false;}}
function resetFilters(){filters.value={market_id:null,product_id:null,type:'',source_platform:'',tag_id:null,duration_min:null,duration_max:null};query.value='';load();} function percent(v:any){return`${Math.round((Number(v)||0)*100)}%`;}
async function adoptPlan(index:number){adopting.value=index;try{const payload={market_id:criteria.value.market_id||null,product_id:criteria.value.product_id||null,content_type:criteria.value.content_type||null,duration:criteria.value.duration||null,keywords:String(criteria.value.keywords||'').split(',').map((w:string)=>w.trim()).filter(Boolean),plan_index:index};const result=(await axios.post('/api/assistant/adopt',payload)).data;ElMessage.success('已采用推荐并创建方案');router.push(`/mix-projects/${result.project.id}`);}catch(e:any){ElMessage.error(e?.response?.data?.detail||'采用方案失败');}finally{adopting.value=null;}}
function blankForm(){return{name:'',title:'',asset_type:'demo',description:'',script_type:'',hook:'',body:'',ending:'',cta:'',template_type:'',structure:'',recommended_duration:20,duration:20,status:'draft',publish_status:'unpublished',notes:'',market_id:null,product_id:null,mix_project_id:null,tags:''};}
function openCreate(){if(resource.value==='mix-projects')return router.push('/mix-projects/create');editing.value=false;selectedFile.value=null;previewUrl.value='';form.value=blankForm();dialog.value=true;} function openEdit(row:any){if(resource.value==='mix-projects')return router.push(`/mix-projects/${row.id}`);editing.value=true;form.value={...row,tags:row.tags_text??row.tags};dialog.value=true;} function showDetail(row:any){if(resource.value==='mix-projects')return router.push(`/mix-projects/${row.id}`);router.push(`/${resource.value}/${row.id}`);} function previewFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(previewUrl.value)URL.revokeObjectURL(previewUrl.value);selectedFile.value=f;previewUrl.value=URL.createObjectURL(f);}
async function save(){const payload:any={};(allowedFields[resource.value]||[]).forEach(k=>{if(form.value[k]!==undefined)payload[k]=form.value[k];});saving.value=true;try{let id=form.value.id;if(editing.value)await axios.put(`${endpoint.value}/${id}`,payload);else{const created=(await axios.post(endpoint.value,payload)).data;id=created.id;if(selectedFile.value){const data=new FormData();data.append('file',selectedFile.value);await axios.post(resource.value==='assets'?`/api/assets/${id}/file`:`/api/videos/${id}/file`,data);}}ElMessage.success('保存成功');dialog.value=false;await loadLookups();await load();}catch(e:any){ElMessage.error(e?.response?.data?.detail||'保存失败');}finally{saving.value=false;}}
async function remove(row:any){try{await ElMessageBox.confirm('删除后无法恢复，确定继续吗？','确认删除',{type:'warning'});await axios.delete(`${endpoint.value}/${row.id}`);ElMessage.success('已删除');await load();}catch{/* cancelled */}}
onMounted(async()=>{try{await loadLookups();}catch{ElMessage.warning('基础数据加载失败');}await load();}); watch(resource,async()=>{rows.value=[];query.value='';dialog.value=false;await loadLookups();await load();});
</script>
