<template>
  <div class="page resource-detail" v-loading="loading">
    <div class="workspace-head"><div><span class="eyebrow">{{ label.toUpperCase() }} DETAIL</span><h1>{{ title || '详情' }}</h1></div><div class="workspace-actions"><el-button @click="router.back()">返回</el-button><el-button type="primary" @click="editing = true">编辑</el-button></div></div>
    <div v-if="item" class="detail-layout">
      <section class="workspace-panel detail-card"><h3>基本信息</h3><div v-for="field in fields" :key="field.key" class="detail-row"><span>{{ field.label }}</span><strong>{{ format(item[field.key]) }}</strong></div></section>
      <section v-if="resource === 'assets'" class="workspace-panel preview-card"><h3>媒体预览</h3><img v-if="isImage" :src="mediaUrl" alt="素材预览"/><video v-else-if="isVideo" :src="mediaUrl" controls/><el-empty v-else description="暂无可预览文件" :image-size="70"/></section>
      <section v-if="resource === 'scripts'" class="workspace-panel text-card"><h3>口播内容</h3><div class="script-block"><b>Hook</b><p>{{ item.hook || '暂无' }}</p></div><div class="script-block"><b>Body</b><p>{{ item.body || '暂无' }}</p></div><div class="script-block"><b>Ending / CTA</b><p>{{ [item.ending, item.cta].filter(Boolean).join(' ') || '暂无' }}</p></div></section>
      <section v-if="resource === 'templates'" class="workspace-panel text-card"><h3>模板结构</h3><pre>{{ item.structure || '暂无结构说明' }}</pre></section>
      <section v-if="resource === 'videos'" class="workspace-panel text-card"><h3>版本与溯源</h3><p>当前版本：{{ item.version || 1 }}</p><p>状态：{{ item.status || 'draft' }}</p><p>关联混剪方案：{{ item.mix_project?.name || '未关联' }}</p></section>
    </div>
    <el-dialog v-model="editing" title="编辑" width="520px"><el-form :model="form" label-width="80px"><el-form-item :label="resource === 'scripts' || resource === 'videos' ? '标题' : '名称'"><el-input v-model="form[titleKey]"/></el-form-item><el-form-item v-if="resource === 'assets'" label="类型"><el-input v-model="form.asset_type"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="editing=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import axios from 'axios'; import { ElMessage } from 'element-plus';
const route = useRoute(); const router = useRouter(); const resource = computed(() => String(route.params.resource)); const id = computed(() => route.params.id); const names: Record<string,string> = { assets:'素材', scripts:'口播脚本', templates:'内容模板', videos:'视频作品' }; const label = computed(() => names[resource.value] || resource.value); const titleKey = computed(() => resource.value === 'scripts' || resource.value === 'videos' ? 'title' : 'name'); const item = ref<any>(null), form = ref<any>({}), loading = ref(false), editing = ref(false);
const configs: Record<string, any[]> = { assets:[['asset_type','类型'],['source_platform','来源平台'],['source_url','来源链接'],['status','状态'],['duration','时长'],['description','描述'],['tags_text','标签']], scripts:[['script_type','脚本类型'],['source_platform','来源平台'],['duration','时长'],['full_text','完整文案'],['notes','备注']], templates:[['template_type','模板类型'],['recommended_duration','建议时长'],['description','描述'],['tags_text','标签']], videos:[['version','版本'],['status','状态'],['publish_status','发布状态'],['duration','时长'],['file_path','文件路径'],['notes','备注']]}; const fields = computed(() => (configs[resource.value] || []).map(([key,label]) => ({key,label})));
const title = computed(() => item.value?.[titleKey.value]); const mediaUrl = computed(() => item.value?.file_path ? `/storage/${String(item.value.file_path).replaceAll('\\','/')}` : ''); const isImage = computed(() => /\.(jpg|jpeg|png|webp)$/i.test(mediaUrl.value)); const isVideo = computed(() => /\.(mp4|mov|webm)$/i.test(mediaUrl.value));
function format(value: any) { return value === null || value === undefined || value === '' ? '暂无' : String(value); }
async function load() { loading.value = true; try { item.value = (await axios.get(`/api/${resource.value}/${id.value}`)).data; form.value = { ...item.value }; } catch { ElMessage.error('详情加载失败'); } finally { loading.value = false; } }
async function save() { const payload: any = {}; payload[titleKey.value] = form.value[titleKey.value]; if (resource.value === 'assets') { payload.asset_type = form.value.asset_type; payload.description = form.value.description; } try { item.value = (await axios.put(`/api/${resource.value}/${id.value}`, payload)).data; editing.value = false; ElMessage.success('保存成功'); } catch (error: any) { ElMessage.error(error?.response?.data?.detail || '保存失败'); } }
onMounted(load);
</script>
