<template>
  <div class="page">
    <div v-if="!isAssistant" class="toolbar"><el-input v-model="query" placeholder="搜索名称、描述或标签" clearable @keyup.enter="load"/><el-button type="primary" @click="openCreate">新增{{ label }}</el-button></div>
    <section v-if="isSearchable" class="filter-bar">
      <el-select v-model="filters.market_id" placeholder="全部市场" clearable filterable><el-option v-for="item in markets" :key="item.id" :label="item.name" :value="item.id"/></el-select>
      <el-select v-model="filters.product_id" placeholder="全部产品" clearable filterable><el-option v-for="item in products" :key="item.id" :label="item.name" :value="item.id"/></el-select>
      <el-input v-model="filters.type" placeholder="内容类型" clearable/><el-input v-if="resource !== 'templates'" v-model="filters.source_platform" placeholder="来源平台" clearable/>
      <el-select v-if="resource !== 'templates'" v-model="filters.tag_id" placeholder="全部标签" clearable filterable><el-option v-for="item in tags" :key="item.id" :label="item.name" :value="item.id"/></el-select>
      <el-input-number v-model="filters.duration_min" placeholder="最短秒数" :min="0" :controls="false"/><el-input-number v-model="filters.duration_max" placeholder="最长秒数" :min="0" :controls="false"/>
      <el-button @click="load">筛选</el-button><el-button text @click="resetFilters">重置</el-button>
    </section>
    <template v-if="isAssistant">
      <section class="assistant-panel"><div><span class="eyebrow">CONTENT CREATION ASSISTANT</span><h2>从需求到混剪方案</h2><p>选择市场、产品、内容类型和时长，系统将推荐分段脚本，并为每段匹配画面素材。</p></div>
        <div class="assistant-form"><el-select v-model="criteria.market_id" placeholder="选择市场" clearable filterable><el-option v-for="item in markets" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="criteria.product_id" placeholder="选择产品" clearable filterable><el-option v-for="item in products" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-input v-model="criteria.content_type" placeholder="内容类型，如 pain_point"/><el-input-number v-model="criteria.duration" :min="1" :max="600"/><el-input v-model="criteria.keywords" placeholder="关键词，用逗号分隔"/><el-button type="primary" @click="load">获取推荐</el-button></div>
      </section>
      <section v-if="hasRecommendations" class="assistant-overview"><div class="section-head"><div><span class="eyebrow">MATCH OVERVIEW</span><h3>推荐匹配概览</h3></div><span class="muted">根据当前推荐结果汇总</span></div><div class="overview-layout"><div class="overview-categories"><div v-for="entry in recommendationOverview" :key="entry.key" class="overview-category"><div><span>{{ entry.title }}</span><strong>{{ entry.best }}%</strong></div><div class="visual-track"><i :style="{ width: `${entry.best}%` }"/></div><small>{{ entry.count }} 条结果</small></div></div><div class="overview-dimensions"><h4>匹配维度均值</h4><div v-for="entry in dimensionOverview" :key="entry.key" class="dimension-row"><span>{{ entry.label }}</span><div class="visual-track"><i :style="{ width: `${entry.value}%` }"/></div><strong>{{ entry.value }}%</strong></div></div></div></section>
      <section class="recommend-section script-recommendations"><div class="section-head"><h3>推荐脚本</h3><span class="muted">选择脚本后直接生成混剪方案</span></div>
        <div v-if="(recommendations.scripts || []).length" class="recommend-list"><article v-for="item in recommendations.scripts" :key="item.id" class="recommend-item script-recommend-item"><div class="recommend-main"><div><strong>{{ item.title }}</strong><small>{{ item.script_type || '未分类' }} · {{ item.duration || 0 }} 秒</small></div><span class="score">{{ percent(item.score) }}</span></div><div class="script-segment-preview"><span v-for="segment in item.segments || []" :key="segment.id" :class="`role-${segment.role}`"><b>{{ roleLabel(segment.role) }}</b>{{ Number(segment.start_second).toFixed(1) }}–{{ Number(segment.end_second).toFixed(1) }}s · {{ segment.spoken_text }}</span></div><div v-if="item.score_breakdown" class="score-breakdown"><span v-for="(value,key) in item.score_breakdown" :key="key">{{ scoreLabels[String(key)] || key }} {{ percent(value) }}</span></div><div class="recommend-actions"><el-button size="small" @click="showDetail(item)">查看脚本</el-button><el-button size="small" type="primary" :loading="adopting === item.id" @click="adoptScript(item)">采用并创建方案</el-button></div></article></div><el-empty v-else description="填写条件后获取推荐脚本" :image-size="70"/>
      </section>
    </template>
    <el-table v-else :data="rows" stripe v-loading="loading" empty-text="暂无数据">
      <el-table-column :label="['scripts','videos'].includes(resource) ? '标题' : '名称'" min-width="180"><template #default="scope">{{ scope.row.name || scope.row.title }}</template></el-table-column><el-table-column v-if="resource === 'assets'" prop="asset_type" label="类型"/><el-table-column v-if="resource === 'scripts'" prop="script_type" label="类型"/><el-table-column v-if="resource === 'templates'" prop="template_type" label="类型"/><el-table-column v-if="resource === 'markets'" prop="country_code" label="国家代码"/><el-table-column v-if="resource === 'products'" prop="category" label="分类"/><el-table-column v-if="['assets','scripts'].includes(resource)" prop="source_platform" label="来源"/><el-table-column v-if="resource === 'scripts'" label="音频" width="100"><template #default="scope"><el-tag :type="scope.row.audio_path ? 'success' : 'info'" effect="plain">{{ scope.row.audio_path ? '已上传' : '未上传' }}</el-tag></template></el-table-column><el-table-column v-if="['assets','videos','mix-projects'].includes(resource)" prop="status" label="状态"/><el-table-column label="操作" width="190" fixed="right"><template #default="scope"><el-button v-if="hasDetail" link type="primary" @click="showDetail(scope.row)">详情</el-button><el-button link @click="openEdit(scope.row)">编辑</el-button><el-button link type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column>
    </el-table>
    <el-dialog v-model="dialog" :title="`${editing ? '编辑' : '新增'}${label}`" :width="resource === 'scripts' ? '960px' : '680px'"><el-form :model="form" label-width="100px"><el-form-item :label="['scripts','videos'].includes(resource) ? '标题' : '名称'"><el-input v-model="form[titleKey]"/></el-form-item>
      <template v-if="resource === 'markets'"><el-form-item label="语言"><el-input v-model="form.language"/></el-form-item><el-form-item label="国家代码"><el-input v-model="form.country_code"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
      <template v-if="resource === 'products'"><el-form-item label="所属市场"><el-select v-model="form.market_id" clearable filterable><el-option v-for="item in markets" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="分类"><el-input v-model="form.category"/></el-form-item><el-form-item label="卖点"><el-input v-model="form.selling_points" type="textarea"/></el-form-item><el-form-item label="目标市场"><el-input v-model="form.target_markets"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
      <template v-if="resource === 'assets'"><el-form-item label="类型"><el-input v-model="form.asset_type" placeholder="pain_point / product / demo"/></el-form-item><el-form-item label="来源平台"><el-input v-model="form.source_platform" placeholder="TikTok / Douyin"/></el-form-item><el-form-item label="来源链接"><el-input v-model="form.source_url"/></el-form-item><div class="form-grid"><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item><el-form-item label="时长（秒）"><el-input-number v-model="form.duration" :min="0" :precision="2"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="active"/><el-option label="归档" value="archived"/></el-select></el-form-item></div><el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="2"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags" placeholder="demo, sunscreen"/></el-form-item></template>
      <template v-if="resource === 'scripts'"><div class="form-grid"><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item></div><div class="form-grid"><el-form-item label="类型"><el-input v-model="form.script_type"/></el-form-item><el-form-item label="总时长"><el-input-number v-model="form.duration" :min="1"/></el-form-item></div><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="口播音频"><div class="audio-upload"><input type="file" accept=".mp3,.wav,.m4a,.aac,.ogg,.webm" @change="previewFile"/><span class="muted">{{ selectedFile?.name || form.audio_file_name || '支持 MP3、WAV、M4A、AAC、OGG' }}</span><audio v-if="previewUrl || form.audio_path" :src="previewUrl || storageUrl(form.audio_path)" controls preload="metadata"/></div></el-form-item><div class="segment-editor-head"><div><strong>分段口播脚本</strong><span class="muted">为每段设置成片时间、文案和画面要求</span></div><el-button size="small" @click="addScriptSegment">添加分段</el-button></div><div class="segment-editor"><article v-for="(segment,index) in scriptSegments" :key="index" class="segment-edit-row"><div class="segment-edit-meta"><el-select v-model="segment.role"><el-option v-for="role in scriptRoles" :key="role.value" :label="role.label" :value="role.value"/></el-select><el-input-number v-model="segment.start_second" :min="0" :precision="1"/><span>至</span><el-input-number v-model="segment.end_second" :min="0.1" :precision="1"/><el-switch v-model="segment.is_key" active-text="重点"/></div><el-input v-model="segment.spoken_text" type="textarea" :rows="2" placeholder="这一时间段的口播文案"/><div class="segment-edit-detail"><el-input v-model="segment.visual_direction" placeholder="画面要求"/><el-select v-model="segment.recommended_asset_type" clearable placeholder="素材类型"><el-option label="使用过程" value="usage"/><el-option label="完成效果" value="result"/><el-option label="引导下单" value="cta"/></el-select><el-input v-model="segment.highlight_text" placeholder="高亮词，用逗号分隔"/><el-button link type="danger" @click="scriptSegments.splice(index,1)">删除</el-button></div></article></div></template>
      <template v-if="resource === 'templates'"><div class="form-grid"><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item></div><el-form-item label="类型"><el-input v-model="form.template_type"/></el-form-item><el-form-item label="结构"><el-input v-model="form.structure" type="textarea" :rows="3"/></el-form-item><el-form-item label="建议时长"><el-input-number v-model="form.recommended_duration" :min="0"/></el-form-item><el-form-item label="标签"><el-input v-model="form.tags"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item></template>
      <template v-if="resource === 'videos'"><div class="form-grid"><el-form-item label="混剪方案"><el-select v-model="form.mix_project_id" clearable filterable><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="市场"><lookup-select v-model="form.market_id" :items="markets"/></el-form-item><el-form-item label="产品"><lookup-select v-model="form.product_id" :items="products"/></el-form-item><el-form-item label="时长"><el-input-number v-model="form.duration" :min="0"/></el-form-item></div><el-form-item label="状态"><el-input v-model="form.status"/></el-form-item><el-form-item label="发布状态"><el-input v-model="form.publish_status"/></el-form-item><el-form-item label="备注"><el-input v-model="form.notes" type="textarea"/></el-form-item></template>
      <el-form-item v-if="!editing && ['assets','videos'].includes(resource)" label="上传文件"><input type="file" :accept="resource === 'assets' ? '.jpg,.jpeg,.png,.webp,.mp4,.mov,.webm' : '.mp4,.mov,.webm'" @change="previewFile"/><div v-if="previewUrl" class="upload-preview"><img v-if="selectedFile?.type.startsWith('image/')" :src="previewUrl" alt="预览"/><video v-else :src="previewUrl" controls/></div></el-form-item>
    </el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, defineComponent, h, onMounted, ref, watch } from 'vue'; import { useRouter } from 'vue-router'; import axios from 'axios'; import { ElMessage, ElMessageBox, ElOption, ElSelect } from 'element-plus';
const props=defineProps<{resource:string}>(); const resource=computed(()=>props.resource); const router=useRouter(); const isAssistant=computed(()=>resource.value==='assistant');
const names:Record<string,string>={markets:'市场',products:'产品',assets:'素材',scripts:'口播脚本',templates:'内容模板','mix-projects':'混剪方案',videos:'视频作品',assistant:'创作助手'}; const label=computed(()=>names[resource.value]||resource.value); const titleKey=computed(()=>['scripts','videos'].includes(resource.value)?'title':'name'); const endpoint=computed(()=>`/api/${resource.value}`); const isSearchable=computed(()=>['assets','scripts','templates'].includes(resource.value)); const hasDetail=computed(()=>['markets','products','assets','scripts','templates','videos','mix-projects'].includes(resource.value));
const ASSISTANT_STORAGE_KEY='content-assistant-state-v2'; const rows=ref<any[]>([]),query=ref(''),loading=ref(false),saving=ref(false),dialog=ref(false),editing=ref(false),form=ref<any>({}); const markets=ref<any[]>([]),products=ref<any[]>([]),tags=ref<any[]>([]),projects=ref<any[]>([]); const filters=ref<any>({market_id:null,product_id:null,type:'',source_platform:'',tag_id:null,duration_min:null,duration_max:null}); const criteria=ref<any>({market_id:null,product_id:null,content_type:'',duration:20,keywords:''}),recommendations=ref<any>({}),adopting=ref<number|null>(null); const selectedFile=ref<File|null>(null),previewUrl=ref(''),scriptSegments=ref<any[]>([]);
const scriptRoles=[{value:'hook',label:'Hook'},{value:'body',label:'Body'},{value:'ending',label:'Ending'},{value:'cta',label:'CTA'}]; const recommendationSections=[{key:'scripts',title:'推荐脚本',limit:5}]; const scoreLabels:Record<string,string>={market:'市场',product:'产品',content_type:'类型',semantic:'语义',duration:'时长'};
const hasRecommendations=computed(()=>recommendationSections.some(section=>(recommendations.value[section.key]||[]).length));
const recommendationOverview=computed(()=>recommendationSections.map(section=>{const items=recommendations.value[section.key]||[];return{key:section.key,title:section.title.replace('推荐',''),count:items.length,best:Math.round(Math.max(0,...items.map((item:any)=>Number(item.score)||0))*100)}}));
const dimensionOverview=computed(()=>Object.entries(scoreLabels).map(([key,label])=>{const values=recommendationSections.flatMap(section=>(recommendations.value[section.key]||[]).map((item:any)=>Number(item.score_breakdown?.[key])).filter(Number.isFinite));return{key,label,value:values.length?Math.round(values.reduce((sum,value)=>sum+value,0)/values.length*100):0}}));
const allowedFields:Record<string,string[]>={markets:['name','language','country_code','description'],products:['name','category','selling_points','target_markets','tags','description','market_id'],assets:['name','asset_type','source_platform','source_url','market_id','product_id','duration','status','description','tags'],scripts:['title','source_platform','source_url','market_id','product_id','script_type','hook','body','ending','cta','duration','full_text','tags','notes'],templates:['name','market_id','product_id','template_type','structure','recommended_duration','description','tags'],videos:['title','mix_project_id','market_id','product_id','duration','status','publish_status','notes'],'mix-projects':['name']};
const LookupSelect=defineComponent({props:{modelValue:{default:null},items:{type:Array,default:()=>[]}},emits:['update:modelValue'],setup(p,{emit}){return()=>h(ElSelect,{modelValue:p.modelValue,clearable:true,filterable:true,'onUpdate:modelValue':(v:any)=>emit('update:modelValue',v)},()=> (p.items as any[]).map(item=>h(ElOption,{key:item.id,label:item.name,value:item.id})));}});
async function loadLookups(){const [m,p,t,mp]=await Promise.all([axios.get('/api/markets'),axios.get('/api/products'),axios.get('/api/tags'),axios.get('/api/mix-projects')]);markets.value=m.data;products.value=p.data;tags.value=t.data;projects.value=mp.data;}
function requestParams(){const p:any={q:query.value||undefined,market_id:filters.value.market_id||undefined,product_id:filters.value.product_id||undefined,source_platform:filters.value.source_platform||undefined,tag_id:filters.value.tag_id||undefined,duration_min:filters.value.duration_min??undefined,duration_max:filters.value.duration_max??undefined};if(filters.value.type)p[resource.value==='assets'?'asset_type':resource.value==='scripts'?'script_type':'template_type']=filters.value.type;return p;}
async function load(){loading.value=true;try{if(isAssistant.value){const payload={market_id:criteria.value.market_id||null,product_id:criteria.value.product_id||null,content_type:criteria.value.content_type||null,duration:criteria.value.duration||null,keywords:String(criteria.value.keywords||'').split(',').map((w:string)=>w.trim()).filter(Boolean)};recommendations.value=(await axios.post('/api/assistant/recommend',payload)).data;}else rows.value=(await axios.get(endpoint.value,{params:requestParams()})).data;}catch(e:any){ElMessage.error(e?.response?.data?.detail||'加载失败');}finally{loading.value=false;}}
function restoreAssistantState(){try{const saved=sessionStorage.getItem(ASSISTANT_STORAGE_KEY);if(!saved)return;const state=JSON.parse(saved);if(state?.criteria)criteria.value={...criteria.value,...state.criteria};if(state?.recommendations)recommendations.value=state.recommendations;}catch{sessionStorage.removeItem(ASSISTANT_STORAGE_KEY);}}
function persistAssistantState(){if(!isAssistant.value)return;sessionStorage.setItem(ASSISTANT_STORAGE_KEY,JSON.stringify({criteria:criteria.value,recommendations:recommendations.value}));}
function resetFilters(){filters.value={market_id:null,product_id:null,type:'',source_platform:'',tag_id:null,duration_min:null,duration_max:null};query.value='';load();} function percent(v:any){return`${Math.round((Number(v)||0)*100)}%`;}
function roleLabel(role:string){return scriptRoles.find(item=>item.value===role)?.label||role;}
async function adoptScript(item:any){adopting.value=item.id;try{const payload={market_id:criteria.value.market_id||null,product_id:criteria.value.product_id||null,content_type:criteria.value.content_type||null,duration:criteria.value.duration||null,keywords:String(criteria.value.keywords||'').split(',').map((w:string)=>w.trim()).filter(Boolean),script_id:item.id};const result=(await axios.post('/api/assistant/adopt',payload)).data;ElMessage.success('已按分段脚本创建混剪方案');router.push(`/mix-projects/${result.project.id}`);}catch(e:any){ElMessage.error(e?.response?.data?.detail||'采用方案失败');}finally{adopting.value=null;}}
function blankForm(){return{name:'',title:'',asset_type:'demo',description:'',script_type:'',hook:'',body:'',ending:'',cta:'',template_type:'',structure:'',recommended_duration:20,duration:20,status:'draft',publish_status:'unpublished',notes:'',market_id:null,product_id:null,mix_project_id:null,tags:''};}
function clearPreview(){if(previewUrl.value)URL.revokeObjectURL(previewUrl.value);selectedFile.value=null;previewUrl.value='';}
function defaultScriptSegments(){return[{role:'hook',start_second:0,end_second:3,spoken_text:'',visual_direction:'',recommended_asset_type:'usage',is_key:true,highlight_text:''},{role:'body',start_second:3,end_second:14,spoken_text:'',visual_direction:'',recommended_asset_type:'usage',is_key:false,highlight_text:''},{role:'ending',start_second:14,end_second:17,spoken_text:'',visual_direction:'',recommended_asset_type:'result',is_key:true,highlight_text:''},{role:'cta',start_second:17,end_second:20,spoken_text:'',visual_direction:'',recommended_asset_type:'cta',is_key:true,highlight_text:''}];}
function addScriptSegment(){const start=scriptSegments.value.length?Number(scriptSegments.value.at(-1).end_second):0;scriptSegments.value.push({role:'body',start_second:start,end_second:start+3,spoken_text:'',visual_direction:'',recommended_asset_type:'usage',is_key:false,highlight_text:''});}
function segmentPayload(item:any,index:number,scriptId:number){return{script_id:scriptId,order_index:index,role:item.role,start_second:item.start_second,end_second:item.end_second,spoken_text:String(item.spoken_text||'').trim(),visual_direction:item.visual_direction||null,recommended_asset_type:item.recommended_asset_type||null,is_key:Boolean(item.is_key),highlight_text:item.highlight_text||null,notes:item.notes||null};}
function openCreate(){if(resource.value==='mix-projects')return router.push('/mix-projects/create');editing.value=false;clearPreview();form.value=blankForm();scriptSegments.value=resource.value==='scripts'?defaultScriptSegments():[];dialog.value=true;} async function openEdit(row:any){if(resource.value==='mix-projects')return router.push(`/mix-projects/${row.id}`);editing.value=true;clearPreview();form.value={...row,tags:row.tags_text??row.tags};scriptSegments.value=resource.value==='scripts'?(await axios.get(`/api/scripts/${row.id}/segments`)).data:[];dialog.value=true;} function showDetail(row:any){if(resource.value==='mix-projects')return router.push(`/mix-projects/${row.id}`);router.push(`/content/${resource.value}/${row.id}`);} function previewFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(previewUrl.value)URL.revokeObjectURL(previewUrl.value);selectedFile.value=f;previewUrl.value=URL.createObjectURL(f);} function storageUrl(path:string){return path?`/storage/${String(path).replaceAll('\\','/')}`:'';}
async function save(){const payload:any={};(allowedFields[resource.value]||[]).forEach(k=>{if(form.value[k]!==undefined)payload[k]=form.value[k];});saving.value=true;try{let id=form.value.id;if(editing.value)await axios.put(`${endpoint.value}/${id}`,payload);else{const created=(await axios.post(endpoint.value,payload)).data;id=created.id;}if(resource.value==='scripts'){const segments=scriptSegments.value.filter(item=>String(item.spoken_text||'').trim()).map((item,index)=>segmentPayload(item,index,id));await axios.put(`/api/scripts/${id}/segments`,segments);}if(selectedFile.value){const uploadEndpoint=resource.value==='assets'?`/api/assets/${id}/file`:resource.value==='videos'?`/api/videos/${id}/file`:resource.value==='scripts'?`/api/scripts/${id}/audio`:'';if(uploadEndpoint){const data=new FormData();data.append('file',selectedFile.value);await axios.post(uploadEndpoint,data);}}ElMessage.success('保存成功');dialog.value=false;clearPreview();await loadLookups();await load();}catch(e:any){ElMessage.error(e?.response?.data?.detail||'保存失败');}finally{saving.value=false;}}
async function remove(row:any){try{await ElMessageBox.confirm(resource.value==='mix-projects'?'删除方案后，其时间轴会被删除；关联的视频作品会保留并改为未关联方案。确定继续吗？':'删除后无法恢复，确定继续吗？','确认删除',{type:'warning'});await axios.delete(`${endpoint.value}/${row.id}`);ElMessage.success('已删除');await loadLookups();await load();}catch(error:any){if(error!=='cancel'&&error!=='close')ElMessage.error(error?.response?.data?.detail||'删除失败，请稍后重试');}}
watch(criteria,persistAssistantState,{deep:true});watch(recommendations,persistAssistantState,{deep:true});
onMounted(async()=>{if(isAssistant.value)restoreAssistantState();try{await loadLookups();}catch{ElMessage.warning('基础数据加载失败');}if(!isAssistant.value)await load();}); watch(resource,async()=>{rows.value=[];query.value='';dialog.value=false;if(isAssistant.value)restoreAssistantState();await loadLookups();if(!isAssistant.value)await load();});
</script>
